<a href="https://colab.research.google.com/github/ricardocarreras/Bootcamp_DataScience_student/blob/master/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf 

In [2]:
from keras.models import Sequential
from keras.layers import Dense

In [11]:
modelo=Sequential()

In [37]:
#modelo.add(Dense(units=10, activation="sigmoid"), input_shape=("cuantas variables van a entrar"))

modelo.add(Dense(units=10, activation="sigmoid", input_shape=(30, )))
modelo.add(Dense(units=1, activation="sigmoid"))

In [38]:
Modelo1=Sequential([
    Dense(units=10, activation="sigmoid", input_dim=4), 
    Dense(units=10, activation="sigmoid")
])


In [24]:
#Optimizador

In [25]:
modelo.compile(loss="binary_crossentropy", 
               optimizer="sgd",
               metrics=["accuracy"]
)

In [27]:
modelo.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                50        
                                                                 
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dense_4 (Dense)             (None, 1)                 11        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [33]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test=train_test_split(load_breast_cancer().data, load_breast_cancer().target, test_size=0.25, random_state=0)




In [41]:
Escalado=StandardScaler().fit(X_train)

In [39]:
import matplotlib.pyplot as plt


In [ ]:
#plt.plot(Modelo100.history["accuracy"])

In [ ]:
#plt.plot(Modelo2.history["accuracy"])

In [ ]:
#modelo.predict(X_test_escalado)

In [ ]:
#modelo.evaluate(X_test_escalado, y_test)

Regresión

In [44]:
from sklearn.datasets import make_regression

In [45]:
X, y=make_regression(n_samples=50000, n_features=3, random_state=0)

In [46]:
X

array([[-0.57518657,  0.14977667,  1.08254492],
       [ 0.09578085,  0.2846845 ,  2.00844156],
       [ 0.48512008,  0.16015993, -1.20878093],
       ...,
       [ 0.39436884, -1.34586156,  1.1278689 ],
       [ 0.21145003, -1.280188  ,  0.95535492],
       [ 0.41172465,  0.0953787 , -0.1013019 ]])

In [47]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=1234)

In [48]:
Escalado=StandardScaler().fit(X_train)

In [55]:
X_train_escalado=Escalado.transform(X_train)
X_test_escalado=Escalado.transform(X_test)

In [50]:
y

array([ 14.18689238, 140.17253253, -23.80832289, ...,  77.99860496,
        50.91512453,  36.13532202])

In [51]:
modelo_R=Sequential()

In [53]:
modelo_R.add(Dense(8, input_dim=3, activation="relu"))
modelo_R.add(Dense(3, activation="linear"))
modelo_R.add(Dense(1, activation="relu"))
modelo_R.compile(loss="mse", optimizer="adam")

In [56]:
modelo_R.fit(X_train_escalado, y_train)

1094/1094 [==============================] - 4s 3ms/step - loss: 8629.1816


In [57]:
y_pred=modelo_R.predict(X_test_escalado)

In [58]:
y_pred

array([[216.68434  ],
       [ 13.088754 ],
       [  0.       ],
       ...,
       [  0.       ],
       [  1.1111057],
       [  0.       ]], dtype=float32)

In [59]:
from sklearn.preprocessing import MinMaxScaler

In [70]:
EscaladoX, EscaladoY=MinMaxScaler().fit(X_train), MinMaxScaler().fit(y_train.reshape(35000, 1))

In [71]:
X_train_reescalado=EscaladoX.fit(X_train)
X_test_reescalado=EscaladoX.fit(X_test)
y_train_reescalado=EscaladoY.transform(y_train.reshape(35000,1))
y_test_reescalado=EscaladoY.transform(y_test.reshape(15000,1))

In [73]:
modelo_R1=Sequential()
modelo_R1.add(Dense(8, input_dim=3, activation="relu"))
modelo_R1.add(Dense(3, activation="linear"))
modelo_R1.add(Dense(1, activation="relu"))
modelo_R1.compile(loss="mse", optimizer="adam")

In [ ]:
modelo_R1.fit(X_train_reescalado, y_train_reescalado, epochs=10)

In [ ]:
EscaladoY=inverse_transform(modelo_R1.predict(X_test_reescalado))