<a href="https://colab.research.google.com/github/ricardocarreras/Bootcamp_DataScience_student/blob/master/kvecinos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:


from scipy import spatial
List1 = [5, 3, 1, 2, 1]
List2 = [0, 3, 1, 4, 2]
List3 = [6, 5, 9, 3, 0]

result = 1 - spatial.distance.cosine(List1, List2, List3)
print(result)

0.5254938542453881


In [ ]:


ListSebas = [5, 3, 1, 2, ]
ListAin = [, 3, 1, 4, 2]
ListCatu = [6, 5, 9, 3, ]
ListYom = [0, 10, 8, , 5]
ListFran=[8, 7, 8, 4, 5]

result = 1 - spatial.distance.cosine(List1, List2, List3)
print(result)

0.5254938542453881


In [1]:
## KNN 

import pandas as pd
import numpy as np
from sklearn import datasets 

In [2]:
from sklearn.neighbors import KNeighborsClassifier 

In [3]:
from sklearn.model_selection import train_test_split

In [5]:
iris=datasets.load_iris()

In [10]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [13]:
df['target'] = iris.target

In [14]:
df.target.unique()

array([0, 1, 2])

In [15]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns='target'),df['target'],test_size=0.3, random_state=1234)

In [16]:
clasificador = KNeighborsClassifier(3)

In [17]:
clasificador

KNeighborsClassifier(n_neighbors=3)

In [18]:
KNeighborsClassifier(n_neighbors=3)

KNeighborsClassifier(n_neighbors=3)

In [19]:
clasificador.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [20]:
KNeighborsClassifier(n_neighbors=3)

KNeighborsClassifier(n_neighbors=3)

In [21]:
y_pred = clasificador.predict(X_test)

In [22]:
y_pred

array([1, 1, 2, 0, 1, 0, 0, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2, 0, 2, 1, 1, 1,
       1, 1, 2, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2,
       2])

In [25]:
pd.crosstab(y_test,y_pred)

col_0    0   1   2
target            
0       16   0   0
1        0  17   0
2        0   1  11

In [29]:
from sklearn.metrics import accuracy_score



In [32]:
accuracy_score(y_pred,y_test)

0.9777777777777777

In [34]:
clasificador.kneighbors([X_test.loc[20]]) # da la distancia - en este caso minkowski - de todas las variables a cada punto que especifica
# distancia de 0.28 entre la linea 20 y la linea 57

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


(array([[0.28284271, 0.36055513, 0.36055513]]), array([[57, 66, 29]]))

In [35]:
clasificador.predict_proba([X_test.loc[20]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([[1., 0., 0.]])

In [36]:
clasificador1=KNeighborsClassifier(3, algorithm='brute', leaf_size=40, metric='euclidean')

In [37]:
clasificador1.fit(X_train,y_train)
y_pred1 = clasificador1.predict(X_test)

In [39]:
accuracy_score(y_pred1,y_test)

0.9777777777777777