<a href="https://colab.research.google.com/github/ricardocarreras/Bootcamp_DataScience_student/blob/master/regresion_lineal_multivariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

import pandas as pd

In [7]:
Y=np.array([349, 368, 388, 414, 444, 484, 518, 550, 586, 615, 686])

In [4]:
Renta=np.array([388, 408, 433, 465, 498, 538, 574, 614, 656, 699, 748])

In [5]:
Ingreso=np.array([240, 245, 234, 278, 265, 288, 298, 279, 266, 235, 254])

In [12]:
matrizx=np.array([[1,1,1,1,1,1,1,1,1,1,1], [388, 408, 433, 465, 498, 538, 574, 614, 656, 699, 748], [240, 245, 234, 278, 265, 288, 298, 279, 266, 235, 254]])

In [13]:
matrizx

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [388, 408, 433, 465, 498, 538, 574, 614, 656, 699, 748],
       [240, 245, 234, 278, 265, 288, 298, 279, 266, 235, 254]])

In [15]:
from sklearn import datasets

In [16]:
dataset=datasets.load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [17]:
dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [18]:
print(dataset["DESCR"])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [19]:
variable_objetivo=dataset["target"]

In [20]:
variable_independiente=dataset["data"]

In [43]:
nombre_variable_independiente=dataset["feature_names"]

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
LinearRegression?

In [24]:
modelo=LinearRegression()

In [25]:
modelo.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

In [26]:
modelo.fit?

In [44]:
modelo.fit(X=variable_independiente, y=variable_objetivo)

LinearRegression()

In [45]:
modelo.intercept_

36.459488385090125

In [46]:
modelo.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [ ]:
modelo.predict

In [32]:
predicciones=modelo.predict(variable_independiente)

In [33]:
predicciones

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603,
       12.52385753, 17.67103669, 15.83288129, 13.80628535, 15.67833832,
       13.38668561, 15.46397655, 14.70847428, 19.54737285, 20.8764282 ,
       11.45511759, 18.05923295,  8.81105736, 14.28275814, 13.70675891,
       23.81463526, 22.34193708, 23.10891142, 22.91502612, 31.35762569,
       34.21510225, 28.02056414, 25.20386628, 24.60979273, 22.94149176,
       22.09669817, 20.42320032, 18.03655088,  9.10655377, 17.20607751,
       21.28152535, 23.97222285, 27.6558508 , 24.04901809, 15.3618477 ,
       31.15264947, 24.85686978, 33.10919806, 21.77537987, 21.08493555,
       17.8725804 , 18.51110208, 23.98742856, 22.55408869, 23.37308644,
       30.36148358, 25.53056512, 21.11338564, 17.42153786, 20.78

In [34]:
df=pd.DataFrame(variable_independiente, columns=nombre_variable_indepoendiente)

In [35]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [36]:
df["target"]=variable_objetivo

In [37]:
modelo.fit(X=df[nombre_variable_indepoendiente], y=df["target"])

LinearRegression()

In [38]:
import statsmodels.formula.api as smf

In [39]:
pct_entrenamiento=0.8

In [40]:
df_train=df.sample(frac=pct_entrenamiento)

df_test=df[~df.index.isin(df_train.index)]

In [41]:
print(df_train.shape)
print(df_test.shape)
print(df.shape)

(405, 14)
(101, 14)
(506, 14)


In [ ]:
model=smf.ols("target~CRIM + ZN+ INDUS + CHAS + NOS ")

In [42]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(df_test["target"], )